language: node_js
node_js:
    - "4.1"
before_install:
    # - export PHANTOMJS_BIN=/usr/local/phantomjs/bin/phantomjs
    # - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
    # - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
    # - sudo rm -rf /usr/local/phantomjs/bin/phantomjs
    # - sudo mv phantomjs /usr/local/phantomjs/bin/phantomjs
    - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get update
    - sudo apt-get install -y gdal-bin imagemagick
before_script:
    - npm install -g grunt-cli
    - mkdir -p test/data
    - pushd test/data
    - sh setup_data.sh
    - popd
script:
    - grunt test
notifications:
    email: false
